# Generated by Django 6.0.2 on 2026-02-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeout", "0008_merge_0005_note_0007_user_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
