# Generated by Django 4.2.28 on 2026-03-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeout', '0009_user_focus_started_at_focussession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='focus_started_at',
        ),
        migrations.DeleteModel(
            name='FocusSession',
        ),
    ]
