# Generated by Django 4.2.28 on 2026-03-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeout', '0010_event_allow_conflict_event_is_global_and_more'),
        ('timeout', '0010_remove_user_focus_started_at_delete_focussession'),
    ]

    operations = [
    ]
