# Generated by Django 6.0.2 on 2026-03-02 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeout', '0011_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='event',
            new_name='deadline',
        ),
    ]
