# Generated by Django 6.0.2 on 2026-03-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeout', '0012_user_focus_started_at_focussession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_note_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longest_note_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='note_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
