# Generated by Django 6.0.2 on 2026-03-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeout", "0012_user_focus_started_at_focussession"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="actual_duration_hours",
            field=models.FloatField(
                blank=True,
                help_text="Actual hours taken (completed_at - created_at).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the event was marked as completed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="estimated_hours",
            field=models.FloatField(
                default=1.0, help_text="Estimated hours to complete this event/task."
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_suggestion",
            field=models.BooleanField(
                default=False,
                help_text="True if this is an AI-suggested block, not a fixed event.",
            ),
        ),
    ]
