# Generated by Django 6.0.2 on 2026-03-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeout', '0013_gamification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='colorblind_mode',
            field=models.CharField(choices=[('none', 'None'), ('protanopia', 'Protanopia (Red-blind)'), ('deuteranopia', 'Deuteranopia (Green-blind)'), ('tritanopia', 'Tritanopia (Blue-blind)')], default='none', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_study_reminder',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='default_note_category',
            field=models.CharField(blank=True, choices=[('', 'None'), ('lecture', 'Lecture'), ('todo', 'To-Do'), ('study_plan', 'Study Plan'), ('personal', 'Personal'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='font_size',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_sounds',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pomo_long_break',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='user',
            name='pomo_short_break',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='user',
            name='pomo_work_minutes',
            field=models.PositiveSmallIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Default')], default='light', max_length=10),
        ),
    ]
