# Generated by Django 6.0.2 on 2026-03-12 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeout', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Optional deadline for this note', null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='time_spent_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Total Pomodoro minutes spent on this note'),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_focus_goal',
            field=models.PositiveSmallIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_notes_goal',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_pomo_goal',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.CreateModel(
            name='StudyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pomodoros', models.PositiveSmallIntegerField(default=0)),
                ('notes_created', models.PositiveSmallIntegerField(default=0)),
                ('focus_minutes', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='timeout_studylog_user_date_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
