# Generated by Django 6.0.2 on 2026-03-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeout', '0016_notes_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
