# Generated by Django 6.0.2 on 2026-03-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeout', '0017_notification_is_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_online',
            field=models.BooleanField(default=False),
        ),
    ]
