# Generated by Django 6.0.2 on 2026-03-13 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeout', '0018_add_auto_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='timeout.conversation'),
        ),
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='timeout.post'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('deadline', 'Deadline'), ('event', 'Event'), ('message', 'Message'), ('like', 'Like'), ('comment', 'Comment'), ('bookmark', 'Bookmark'), ('follow', 'Follow'), ('exam', 'Exam'), ('class', 'Class'), ('meeting', 'Meeting'), ('study_session', 'Study Session')], default='deadline', max_length=20),
        ),
    ]
