# Generated by Django 6.0.2 on 2026-03-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeout', '0019_notification_conversation_notification_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(),
        ),
    ]
