# Generated by Django 6.0.2 on 2026-03-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeout', '0020_remove_content_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='studylog',
            name='notes_edited',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
