# Generated by Django 6.0.2 on 2026-03-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeout', '0021_add_notes_edited_to_studylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='page_mode',
            field=models.CharField(choices=[('pageless', 'Pageless'), ('paged', 'Paged')], default='pageless', max_length=10),
        ),
    ]
