# Generated by Django 6.0.2 on 2026-03-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeout', '0023_add_follow_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='linked_study_sessions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'event_type': 'study_session'}, related_name='linked_deadlines', to='timeout.event'),
        ),
    ]
