# Generated by Django 6.0.2 on 2026-03-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeout', '0024_add_postflag_and_user_ban'),
        ('timeout', '0024_event_linked_study_sessions'),
    ]

    operations = [
    ]
