# Generated by Django 5.2.11 on 2026-03-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeout', '0028_notification_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='allow_conflict',
        ),
    ]
