# Generated by Django 6.0.2 on 2026-03-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeout', '0029_remove_allow_conflict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='daily_study_reminder',
        ),
    ]
